image: Visual Studio 2017

skip_commits:
  files:
    - '**/*.md'

build_script:
  - cmd: msbuild /t:restore
  - cmd: msbuild /t:pack /p:PackageOutputPath=%APPVEYOR_BUILD_FOLDER%

artifacts:
  - path: '*.nupkg'

deploy:
  provider: NuGet
  server: https://www.myget.org/F/msbuildsdkextras/api/v2/package
  api_key:
    secure: bmqlJK8a5HYiUXOT99HXT1j7JiM5+fpR4kHhxIC30oaaEXbv94f0fKdiKlU1QC/l
  artifact: /.*\.nupkg/
