image: Visual Studio 2015

build_script:
  - cmd: nuget pack MSBuild.Sdk.Extras.nuspec -Version 1.0.0-rc4.%APPVEYOR_BUILD_NUMBER% -NoPackageAnalysis
  
artifacts:
  - path: '*.nupkg'
  
deploy:
  provider: NuGet
  server: https://www.myget.org/F/msbuildsdkextras/api/v2/package
  api_key:
    secure: bmqlJK8a5HYiUXOT99HXT1j7JiM5+fpR4kHhxIC30oaaEXbv94f0fKdiKlU1QC/l
  artifact: /.*\.nupkg/
